# Dream Memory - Ollama Vision Config
# No API keys required

# Vision backend (Ollama only)
VISION_BACKEND = "ollama"
OLLAMA_HOST = "http://localhost:11434"
OLLAMA_URL = "http://localhost:11434/api/generate"

# Ollama model
OLLAMA_MODEL = "qwen2.5vl:3b"

# Timing
GEOMETRY_REFRESH_MS = 1000
ANALYSIS_TIMEOUT_SECONDS = 60

# Image
JPEG_QUALITY = 25
MAX_WIDTH = 640

# Limits
MAX_REQUESTS = 20
CONFIDENCE_MIN = 10

# Request bar (at BOTTOM of screen)
REQUEST_BAR_HEIGHT_RATIO = 0.24

# Startup behavior - DISABLED BY DEFAULT
AUTO_ANALYZE_ON_START = False
AUTO_WATCH_REQUEST_BAR = False

# Status values
STATUS_LIVE = "LIVE"
STATUS_ANALYZING = "ANALYZING..."
STATUS_NO_MARKS = "NO MARKS"
STATUS_API_ERROR = "API ERROR"
STATUS_WAITING = "WAITING..."
STATUS_READY = "READY"
STATUS_STOPPED = "STOPPED"
STATUS_NO_WINDOW = "NO WINDOW"

# Error messages
ERR_NO_AI = "NO AI BACKEND"
ERR_NO_WINDOW = "NO WINDOW"
